import Head from "next/head";
import { Inter } from "next/font/google";
import DronePage from "./dronePage";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>ThreeJs Test</title>
        <meta name="description" content="Generated by Aalap" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DronePage />
      </main>
    </>
  );
}
